# Use the Jaeger all-in-one image
FROM jaegertracing/all-in-one:1.62.0

# Set environment variables
ENV COLLECTOR_ZIPKIN_HTTP_PORT=9411

# Expose the required ports
EXPOSE 5775/udp
EXPOSE 6831/udp
EXPOSE 6832/udp
EXPOSE 5778
EXPOSE 16686
EXPOSE 14268
EXPOSE 9411
EXPOSE 4317
EXPOSE 4318
