services:
  jaeger:
    build:
      context: ../../../
      dockerfile: ./src/main/docker/Dockerfile.jaeger
    container_name: jaeger
    ports:
      - "16686:16686" # Optional, for host access
    restart: always
    networks:
      - monitoring

  quarkus-backend:
    build:
      context: ../../../
      dockerfile: ./target/Dockerfile.jvm
    container_name: quarkus-backend
    ports:
      - "8080:8080" # Optional, for host access
    restart: always
    networks:
      - monitoring

  db:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - monitoring

  #  adminer:
  #    image: adminer
  #    restart: always
  #    ports:
  #      - 8090:8080

  # https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.20
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./db-postgres/pgadmin:/root/.pgadmin
    ports:
      - 8090:80
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
