= Besprechungsprotokoll 17.10.2023
david lehner
1.0, 2023-10-17: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

| David Lehner
|

| Anton Cao
|

| Alexander Nikolaus
|

| Fröller Felix
|

|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|HTBLA Leonding (Unterricht)

|von-bis
|Di. 17.10.2023, 5. EH
|Dauer
|15 min
|===



== Besprochene Themen

* Wie kann man Fälschungssicherheit in Wahlsituationen herstellen (Blockchain)
* Proof of Concept erstellen: können Wahlen online sicher ablaufen?
Ist die Verwendung von Blockchain sinnvoll? Gibt es andere Technologien
* MVP ausgemacht. List von Wahlkandidaten eingeben und auslesen.


== Vereinbarungen und Entscheidungen

.Was wurde vereinbart?
[%autowidth]
|===
|wer |macht was |bis wann

| leovote-Team
a| Einarbeitung in Blockchain technologie.
Daten in Blockchain speichern (minimal).
Ist sie verwendbar in unserem Bereich? (Doku erstellen)
Eine Liste der Wahlteilnehmer soll eingegeben und ausgelesen werden.
Datenmodell dazu erstellen (Wahl + Wahlteilnehmer)
| 07.11.23
|===
