= LeoVote Backend Documentation
:toc:
:icons: font

This is the documentation for the backend of the LeoVote project.
The backend is written in Java and uses Quarkus as the framework.

== Prerequisites

Before starting, ensure you have the following installed:

* JDK 21
* Quarkus CLI (optional)
* Docker

== Start the backend

* Open your terminal and go to backend folder
[source, bash]
----
cd backend
----
.Set up Postgres-DB

[%collapsible]
====
Terminal:
[source, bash]
----
cd backend
----
Create and start database:

[source, bash]
----
postgres-download-scripts-16.3.sh
./postgres-create-db.sh
./postgres-start.sh
----
Datasource in IntelliJ IDEA:

1. Open datasource.txt
2. Copy datasource.txt
3. On `database` option -> `{plus}`
4. Import from Clipboard
5. Download latest driver
6. Password: app
7. Test connection
8. Click ok
====

To start the backend, run the following command in the root directory of the backend project:

If you have the Quarkus CLI installed:

[source,shell]
----
quarkus dev --clean
----

If you don't have the Quarkus CLI installed:

[source,shell]
----
./mvnw compile quarkus:dev
----
