@startuml

top to bottom direction
skinparam linetype ortho

class Candidate {
  - schoolId: String
  - grade: String
  - id: Long
  - lastName: String
  - firstName: String
}

class Election {
  - electionStart: LocalDateTime
  - electionType: String
  - electionEnd: LocalDateTime
  - name: String
  - id: Long
  - voteables: List<Candidate>
}

class HasVoted {
  - voted: boolean
  - hasVotedId: HasVotedId
}

class HasVotedId {
  - election: Election
  - voter: Voter
}

class Vote {
  - candidate: Candidate
  - id: Long
  - election: Election
}

class Voter {
  - id: Long
  - schoolId: String
  - password: String
}

HasVoted   "1" *-[#595959,plain]-> "hasVotedId\n1" HasVotedId
HasVoted    -[#595959,dashed]->  HasVotedId : "«create»"
HasVotedId "1" *-[#595959,plain]-> "election\n1" Election
HasVotedId "1" *-[#595959,plain]-> "voter\n1" Voter
Vote       "1" *-[#595959,plain]-> "candidate\n1" Candidate
Vote       "1" *-[#595959,plain]-> "election\n1" Election

@enduml
