@startuml

top to bottom direction

class Candidate {
  - schoolId: String
  - grade: String
  - firstName: String
  - lastName: String
}
class Election {
  - participatingCandidates: List<Candidate>
  - electionEnd: LocalDateTime
  - electionType: String
  - name: String
  - electionStart: LocalDateTime
}
class HasVoted {
  - election: Election
  - voter: Voter
  - voted: boolean
}
class Vote {
  - candidate: Candidate
  - election: Election
}
class Voter {
  - schoolId: String
  - password: String
}

Election  "*" *-[#595959,plain]-> "*" Candidate
HasVoted  "*" *-[#595959,plain]-> "1" Election
HasVoted  "*" *-[#595959,plain]-> "1" Voter
Vote      "*" *-[#595959,plain]-> "1" Candidate
Vote      "*" *-[#595959,plain]-> "1" Election
@enduml
