### get access token

POST https://auth.htl-leonding.ac.at/realms/htl-leonding/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = htlleonding-service &
client_secret = AkIRaaboJ23Q64jSjtN9gkmfMumUybD8 &
grant_type = password &
username = {{username}} &
password = {{password}} &
  #username = student &
  #password = passme &
scope = openid

> {%
    client.global.set("auth_token", response.body.access_token);
    client.log("Bearer: " + client.global.get("auth_token"));
%}

###

GET https://auth.htl-leonding.ac.at/realms/htl-leonding/protocol/openid-connect/userinfo
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###