### Get all candidates
GET http://localhost:8080/candidates

### Get candidate by ID
GET http://localhost:8080/candidates/1

### Get candidate by school ID
#GET http://localhost:8080/candidates/school-id/id123

### Create a new candidate
POST http://localhost:8080/candidates
Content-Type: application/json

{
  "schoolId": "newStudent",
  "firstName": "Hans",
  "lastName": "Meier",
  "password": "newPassword"
}

### Update candidate by ID
PUT http://localhost:8080/candidates/1
Content-Type: application/json

{
  "schoolId": "updatedStudent",
  "firstName": "UpdatedHans",
  "lastName": "UpdatedMeier",
  "password": "updatedPassword"
}

### Delete candidate by ID
DELETE http://localhost:8080/candidates/3

### Delete candidate by school ID
#DELETE http://localhost:8080/candidates/school-id/id123
