### Get all Elections
GET http://localhost:8080/elections

### Get Election by ID
GET http://localhost:8080/elections/1

### Get Result from Election
GET http://localhost:8080/elections/results/2

### Get Emails from Election
GET http://localhost:8080/elections/emails/1

### Add Email to Election
POST http://localhost:8080/elections/addEmail/1/david.spetzi@gmail.com

### Delete Email from election
DELETE http://localhost:8080/elections/removeEmail/1

### Create a new election
POST http://localhost:8080/elections
Content-Type: application/json

{
  "name": "Election2",
  "electionStart": "2023-11-18T12:00:00",
  "electionEnd": "2023-11-20T12:00:00",
  "electionType": "Crosses",
  "participatingCandidates": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

### Update Election by ID
PUT http://localhost:8080/elections/1
Content-Type: application/json

{
  "name": "UpdatedElection",
  "electionStart": "2023-11-19T12:00:00",
  "electionEnd": "2023-11-21T12:00:00",
  "electionType": "Boxes",
  "participatingCandidates": [
    {
      "id": 1
    }
  ]
}


### Delete election by ID
DELETE http://localhost:8080/elections/2
