### Get all has-voted
GET http://localhost:8080/has-voted

### Get has-voted by ID
GET http://localhost:8080/has-voted/1

### Create a new has-voted
POST http://localhost:8080/has-voted
Content-Type: application/json

{
  "election": {
    "id": 1
  },
  "voter": {
    "id": 2
  },
  "voted": true
}


### Delete has-voted by ID
DELETE http://localhost:8080/has-voted/1
