### Get all Votes
GET http://localhost:8080/votes

### Get Votes by ID
GET http://localhost:8080/votes/1

### Create a new Vote
POST http://localhost:8080/votes
Content-Type: application/json

{
  "candidate": {
    "id": 1
  },
  "election": {
    "id": 1
  }
}

### Update A Vote by ID
PUT http://localhost:8080/votes/1
Content-Type: application/json

{
  "candidate": {
    "id": 1
  },
  "election": {
    "id": 2
  }
}

### Delete Vote by ID
DELETE http://localhost:8080/votes/2
