### Get all voters
GET http://localhost:8080/voters

### Get voter by ID
GET http://localhost:8080/voters/1

### Get voter by school ID
#GET http://localhost:8080/voters/school-id/student1

### Create a new voter
POST http://localhost:8080/voters
Content-Type: application/json

{
  "schoolId": "newStudent",
  "password": "newPassword"
}

###

POST http://localhost:8080/voters/vote/2/2
Content-Type: application/json
Accept: application/json

{
  "voterId": "11f2629c-135b-4615-9b01-6db038d0a7eb"
}

###
POST http://localhost:8080/voters/elecetion/2
Content-Type: application/json
Accept: application/json

{
  "voterCount": 10
}


### Update a Voter
PUT http://localhost:8080/voters/1
Content-Type: application/json

{
  "schoolId": "updatedStudent",
  "password": "updatedPassword"
}


### Delete voter by ID
DELETE http://localhost:8080/voters/2

### Delete voter by school ID
#DELETE http://localhost:8080/voters/school-id/student1
