### Get all voters
GET http://localhost:8080/voters

### Get voter by ID
GET http://localhost:8080/voters/voter/fe73da97-7a43-4725-8cb6-9c2b09ddae73

### Create a new voter
POST http://localhost:8080/voters
Content-Type: application/json

{
  "schoolId": "newStudent",
  "password": "newPassword"
}

###

POST http://localhost:8080/voters/vote/1/1
Content-Type: application/json
Accept: application/json

{
  "voterId": "f2b198ea-e917-4dd0-8089-61ac276db31f"
}

###
POST http://localhost:8080/voters/elecetion/2
Content-Type: application/json
Accept: application/json

{
  "voterCount": 10
}

### Update a Voter
PUT http://localhost:8080/voters/1
Content-Type: application/json

{
  "generatedId": "94a39a0f-acfa-4264-8918-7805201dc4df",
  "participatingIn": 1,
  "voted": true
}


### Delete voter by ID
DELETE http://localhost:8080/voters/2
