@startuml

top to bottom direction

class Candidate {
  - schoolId: String
  - grade: String
  - firstName: String
  - lastName: String
}

class Block {
    - index: int
    - timeStamp: Long
    - candidate: Candidate
    - voted: Voter
    - previousHash: String
    - currentBlockHash: String
}

class Blockchain {
    - election: Election
    - blocks: List<Block>
}

class Election {
  - participatingCandidates: List<Candidate>
  - electionEnd: LocalDateTime
  - electionStart: LocalDateTime
  - electionType: String
  - name: String
  - blockchain: Blockchain
}

class Voter {
  - generatedId: Long
  - election: List<Election>
}

Election "1"--"1" Blockchain
Blockchain "1"--"*" Block
Candidate "1"--"*" Block
Voter "*"--"*" Election
@enduml
