= Besprechungsprotokoll 31.01.2025
1.0, 2024-10-25: mom
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend

| Nikolaus Alexander

| Fröller Felix

| Anton Cao

| David Lehner

| Herr Prof. Thomas Stütz

| Herr Prof. Christian Aberger

|===

|===
|nicht anwesend


|===
.Ort und Zeit
[cols=2*]
|===
|Ort
|HTBLA Leonding (Unterricht)

|von-bis
|Fr. 31.01.2025
|Dauer
|
|===

== Besprochene Themen

* Frontend-UI vertikal und horizontal
* Wahl erstellen -> mindestens 1 und eine Warnung, bei Wahl eine Meldung, dass eine Wahl erstellt worden ist
* Wahlübersicht -> sortieren nach der jüngsten Wahl und den Zeitraum angeben, ID weggeben
* Wählen -> eventuell Doppelklick bei Multivalue, Deutscher Name für Multivalue ändern (Mehrwert)
* Anzahl der Stimmen für die einzelenen Punkte

== Vereinbarungen und Entscheidungen

.Was wurde vereinbart?
[%autowidth]
|===
|wer |macht was |bis wann

| Leovote-Team
a|

|
|===