@startuml

class Election {
    - id: Long
    - begin: Date
    - end: Date
    - electionType: ElectionType
}

class Vote {
    - voter: Voter
    - candidate: Candidate
    - election: Election
}

enum ElectionType{
    - Points
    - Crosses
}

class Voter {
    - schoolID: String
    - schoolPassword: String
    - alreadyVoted: Boolean
}

class Candidate {
   - schoolID: String
   - firstname: String
   - lastname: String
   - class: String
}

Vote   "1"--"*" Candidate  : > hat
Vote   "1"--"*" Voter  : < nimmt Teil
Election "1"--"*" Vote : < Teil von
Election -- ElectionType : > ist

@enduml
