name: Build and Deploy Dockerfiles
run-name: ${{ github.actor }} is building Docker Images 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-images:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      # Build Angular Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies & Build Frontend
        run: |
          npm install
          npm run build --prod
        working-directory: ./frontend

      - name: Build Frontend Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/frontend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/backend-deployment.yaml
          kubectl apply -f ./k8s/frontend-deployment.yaml