name: Build and Deploy Dockerfiles
run-name: ${{ github.actor }} is building Docker Images 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-images:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          pwd
          ls -lah
        working-directory: ./k8s

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Chmod +x for build.sh
        run: chmod +x ./backend/build.sh

      - name: Start Postgres DB
        run: |
          chmod +x ./postgres-download-scripts-16.3.sh
          ./postgres-download-scripts-16.3.sh
          ./postgres-create-db.sh
          ./postgres-start.sh
        working-directory: backend

      - name: Build with Maven & Create Package
        run: ./build.sh
        working-directory: backend